export const FOLLOWING_USER_BLOGS_REQUEST = "FOLLOWING_USER_BLOGS_REQUEST"
export const FOLLOWING_USER_BLOGS_SUCCESS = "FOLLOWING_USER_BLOGS_SUCCESS"
export const FOLLOWING_USER_BLOGS_FAIL = "FOLLOWING_USER_BLOGS_FAIL"

export const ALL_BLOGS_REQUEST = "ALL_BLOGS_REQUEST"
export const ALL_BLOGS_SUCCESS = "ALL_BLOGS_SUCCESS"
export const ALL_BLOGS_FAIL = "ALL_BLOGS_FAIL"

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST"
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS"
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL"

export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET"


export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST"
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS"
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL"

export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET"


export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST"
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL"

export const DELETE_BLOG_RESET = "DELETE_BLOG_RESET"


export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST"
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS"
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL"

export const LIKE_BLOG_REQUEST = "LIKE_BLOG_REQUEST"
export const LIKE_BLOG_SUCCESS = "LIKE_BLOG_SUCCESS"
export const LIKE_BLOG_FAIL = "LIKE_BLOG_FAIL"

export const UNLIKE_BLOG_REQUEST = "UNLIKE_BLOG_REQUEST"
export const UNLIKE_BLOG_SUCCESS = "UNLIKE_BLOG_SUCCESS"
export const UNLIKE_BLOG_FAIL = "UNLIKE_BLOG_FAIL"

export const LIKE_BLOG_RESET = "LIKE_BLOG_RESET"

export const BLOG_LIKE_STATUS_REQUEST = "BLOG_LIKE_STATUS_REQUEST"
export const BLOG_LIKE_STATUS_SUCCESS = "BLOG_LIKE_STATUS_SUCCESS"
export const BLOG_LIKE_STATUS_FAIL = "BLOG_LIKE_STATUS_FAIL";


export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const ADD_COMMENT_RESET = "ADD_COMMENT_RESET"

export const ADD_SUBCOMMENT_REQUEST = "ADD_SUBCOMMENT_REQUEST";
export const ADD_SUBCOMMENT_SUCCESS = "ADD_SUBCOMMENT_SUCCESS"
export const ADD_SUBCOMMENT_FAIL = "ADD_SUBCOMMENT_FAIL";

export const LIKE_COMMENT_REQUEST = "LIKE_COMMENT_REQUEST"
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS"
export const LIKE_COMMENT_FAIL = "LIKE_COMMENT_FAIL"

export const LIKE_COMMENT_RESET = "LIKE_COMMENT_RESET"

export const UNLIKE_COMMENT_REQUEST = "UNLIKE_COMMENT_REQUEST"
export const UNLIKE_COMMENT_SUCCESS = "UNLIKE_COMMENT_SUCCESS"
export const UNLIKE_COMMENT_FAIL = "UNLIKE_COMMENT_FAIL"

export const UNLIKE_COMMENT_RESET = "UNLIKE_COMMENT_RESET"

export const COMMENT_LIKE_STATUS_REQUEST = "COMMENT_LIKE_STATUS_REQUEST";
export const COMMENT_LIKE_STATUS_SUCCESS = "COMMENT_LIKE_STATUS_SUCCESS";
export const COMMENT_LIKE_STATUS_FAIL = "COMMENT_LIKE_STATUS_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL"

export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";

export const LIKE_SUBCOMMENT_REQUEST = "LIKE_SUBCOMMENT_REQUEST"
export const LIKE_SUBCOMMENT_SUCCESS = "LIKE_SUBCOMMENT_SUCCESS"
export const LIKE_SUBCOMMENT_FAIL = "LIKE_SUBCOMMENT_FAIL"

export const UNLIKE_SUBCOMMENT_REQUEST = "UNLIKE_SUBCOMMENT_REQUEST"
export const UNLIKE_SUBCOMMENT_SUCCESS = "UNLIKE_SUBCOMMENT_SUCCESS"
export const UNLIKE_SUBCOMMENT_FAIL = "UNLIKE_SUBCOMMENT_FAIL"

export const SUBCOMMENT_LIKE_STATUS_REQUEST = "SUBCOMMENT_LIKE_STATUS_REQUEST";
export const SUBCOMMENT_LIKE_STATUS_SUCCESS = "SUBCOMMENT_LIKE_STATUS_SUCCESS";
export const SUBCOMMENT_LIKE_STATUS_FAIL = "SUBCOMMENT_LIKE_STATUS_FAIL";

export const DELETE_SUBCOMMENT_REQUEST = "DELETE_SUBCOMMENT_REQUEST"
export const DELETE_SUBCOMMENT_SUCCESS = "DELETE_SUBCOMMENT_SUCCESS"
export const DELETE_SUBCOMMENT_FAIL = "DELETE_SUBCOMMENT_FAIL"




