export const GET_INBOX_REQUEST = "GET_INBOX_REQUEST"
export const GET_INBOX_SUCCESS = "GET_INBOX_SUCCESS"
export const GET_INBOX_FAIL = "GET_INBOX_FAIL"


export const MY_CHATS_REQUEST = "MY_CHATS_REQUEST"
export const MY_CHATS_SUCCESS = "MY_CHATS_SUCCESS";
export const MY_CHATS_FAIL = "MY_CHATS_FAIL"

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST"
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL"

export const DELETE_MESSAGE_RESET = "DELETE_MESSAGE_RESET"