export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";


export const  OTP_HELPER_REQUEST = 'OTP_HELPER_REQUEST'
export const  OTP_HELPER_SUCCESS = 'OTP_HELPER_SUCCESS'
export const OTP_HELPER_FAIL = 'OTP_HELPER_FAIL';


export const  RESET_PASSWORD_REQUEST = ' RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = ' RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = ' RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET"


export const LOAD_PROFILE_REQUEST = "LOAD_PROFILE_REQUEST"
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"
export const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"


export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET"


export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"


export const FOLLOWING_STATUS_REQUEST = "FOLLOWING_STATUS_REQUEST"
export const FOLLOWING_STATUS_SUCCESS = "FOLLOWING_STATUS_SUCCESS"
export const FOLLOWING_STATUS_FAIL = "FOLLOWING_STATUS_FAIL"

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST"
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL"

export const UNFOLLOW_USER_REQUEST = "UNFOLLOW_USER_REQUEST"
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS"
export const UNFOLLOW_USER_FAIL = "UNFOLLOW_USER_FAIL"
export const FOLLOW_USER_RESET = "FOLLOW_USER_RESET"

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL"
export const SEARCH_USER_RESET = "SEARCH_USER_RESET"

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST"
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS"
export const ALL_USERS_FAIL = "ALL_USERS_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";
